version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
     - run:
          name: log
          command: |
             echo 'echo ' >> $keystoreurl
             echo 'echo ' >> $pass
             echo 'echo ' >> $alias
             echo 'echo ' >> $keypass

      - run:
          name: Get Release.jks file
          command: |
            curl -o buildSrc/release.jks >> $keystoreurl
      - run:
          name: create release data file
          command: |
            echo project.ext.alias= >> $alias >>buildSrc/properties.gradle
            echo project.ext.pass= >> $pass >>buildSrc/properties.gradle
            echo project.ext.keypass= >> $keypass >>buildSrc/properties.gradle

      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum  "app/build.gradle.kts" }}

      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports

      - run:
          name: Build Apk
          command: ./gradlew assemble
      - store_artifacts:
          path: app/build/outputs/apk
          destination: reports

      - store_test_results:
          path: app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
